# -*- coding: utf-8 -*-
"""tugas2_sinyal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lCbPNtVn1K16mLrPlz_b1j8vV0u66QY5
"""

import numpy as np

def convolution_1d(signal, kernel):
    signal_length = len(signal)
    kernel_length = len(kernel)
    result_length = signal_length + kernel_length - 1
    result = np.zeros(result_length)

    kernel = np.flip(kernel)
    for i in range(result_length):
        for j in range(kernel_length):
            if i - j >= 0 and i - j < signal_length:
                result[i] += signal[i - j] * kernel[j]

    return result

signal = np.array(input("Masukkan data sinyal: ").split(), dtype=float)
kernel = np.array(input("Masukkan data kernel: ").split(), dtype=float)

convolved_signal = convolution_1d(signal, kernel)
print("Ijlal Abdus Salam")
print("5009201014")
print(convolved_signal)